FROM tensorflow/tensorflow:2.10.1-gpu

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN python3 -m pip install --no-cache-dir --upgrade -r /api/requirements.txt

COPY ./api /api

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]